api_platform:
  defaults:
    item_operations: ['get']
    collection_operations: ['get']
    pagination_client_items_per_page: true
    pagination_items_per_page: 15
  collection:
    pagination:
      items_per_page_parameter_name: itemsPerPage
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
  show_webby: false
  title: '酒水营销平台 API 文档'
  #description: 'API 文档'
  version: '0.1.0'
  formats:
    json:
      mime_types: ['application/json']
    jsonld:
      mime_types: ['application/ld+json']
    html:
      mime_types: ['text/html']
  graphql:
    enabled: false
