api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    show_webby: false
    title: '酒水营销平台 API 文档'
    #description: 'API 文档'
    version: '0.1.0'
