vich_uploader:
    db_driver: orm
    metadata:
        #auto_detection: true
        #cache: file
        #type: attribute    # or annotation
        #type: annotation    # or annotation

    mappings:
        imgs:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
