vich_uploader:
    db_driver: orm
    metadata:
        #auto_detection: false
        #cache: file
        #type: attribute    # or annotation
        #type: annotation    # or annotation

    mappings:
        products:
            uri_prefix: /img/product
            upload_destination: '%kernel.project_dir%/public/img/product'
        orgs:
            uri_prefix: /img/org
            upload_destination: '%kernel.project_dir%/public/img/org'
        nodes:
            uri_prefix: /img/node
            upload_destination: '%kernel.project_dir%/public/img/node'
        withdraws:
            uri_prefix: /img/withdraw
            upload_destination: '%kernel.project_dir%/public/img/withdraw'
