App\Entity\MediaObject:
    file:
        mapping: media_object # required
        filename_property: filePath # required
          #size: imageSize
          #mime_type: imageMimeType
          #original_name: imageOriginalName
          #dimensions: imageDimensions
