App\Entity\Org:
    imageFile:
        mapping: orgs # required
        filename_property: img # required
          #size: imageSize
          #mime_type: imageMimeType
          #original_name: imageOriginalName
          #dimensions: imageDimensions
